Done.
Setting up the random seed for reproducibility...
Done.
dynamic_import - class_name:  OracleTrainer
Initializing model...
Done.
Initializing datasets...
Done.
Initializing clients...
dynamic_import - class_name:  OracleClient
Done.
Initializing server...
dynamic_import - class_name:  OracleServer
Running without server optimizer
Running without server optimizer
Done.
Initialize return score, metrics, ckpt, ckpt step...
Setting up metrics...
Done.
Done.
Initializing optimizer and scheduler...
Done.
Generating sample ids for plots...
Done.
dynamic_import - class_name:  OracleClient
The experiment begins...
ROUND 1/4: Training 1 Clients...
CLIENT 1/1: weimar5 RGB
ciaooooooooooooooooooooooooooooooooooooooooooooo4
ciaooooooooooooooooooooooooooooooooooooooooooooo5
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f3e65f39a60>
Traceback (most recent call last):
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1296, in _shutdown_workers
    self._mark_worker_as_unavailable(worker_id, shutdown=True)
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1243, in _mark_worker_as_unavailable
    q.put(None)
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/multiprocessing/queues.py", line 94, in put
    self._start_thread()
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/multiprocessing/queues.py", line 179, in _start_thread
    self._thread.start()
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/threading.py", line 897, in start
    self._started.wait()
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt:
Traceback (most recent call last):
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 49, in <module>
    run_experiment()
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 20, in run_experiment
    max_score = trainer.train(*trainer.train_args, **trainer.train_kwargs)
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 77, in train
    return self.perform_fed_oracle_training(
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 39, in perform_fed_oracle_training
    losses = self.server.train_clients(partial_metric=partial_train_metric)
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/servers/oracle_server.py", line 71, in train_clients
    out = c.train(partial_metric, r=r)
  File "/home/utente/Scrivania/PROVA/LADD/src/clients/oracle_client.py", line 208, in train
    if self.args.local_rank == 0:
  File "/home/utente/Scrivania/PROVA/LADD/src/clients/oracle_client.py", line 178, in run_epoch
    for n, l in dict_all_iters_losses.items():
  File "/home/utente/Scrivania/PROVA/LADD/src/clients/oracle_client.py", line 139, in __exec_epoch
    self.handle_grad()
KeyboardInterrupt