2023-06-14 14:48:13,657 INFO    MainThread:10134 [wandb_setup.py:_flush():69] setting env: {}
2023-06-14 14:48:13,658 INFO    MainThread:10134 [wandb_setup.py:_flush():69] setting login settings: {}
2023-06-14 14:48:13,658 INFO    MainThread:10134 [wandb_init.py:_log_setup():342] Logging user logs to /home/utente/Scrivania/PROVA/LADD/wandb/run-20230614_144813-33ktjcne/logs/debug.log
2023-06-14 14:48:13,659 INFO    MainThread:10134 [wandb_init.py:_log_setup():343] Logging internal logs to /home/utente/Scrivania/PROVA/LADD/wandb/run-20230614_144813-33ktjcne/logs/debug-internal.log
2023-06-14 14:48:13,659 INFO    MainThread:10134 [wandb_init.py:init():375] calling init triggers
2023-06-14 14:48:13,659 INFO    MainThread:10134 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2023-06-14 14:48:13,660 INFO    MainThread:10134 [wandb_init.py:init():424] starting backend
2023-06-14 14:48:13,660 INFO    MainThread:10134 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-06-14 14:48:13,688 INFO    MainThread:10134 [backend.py:ensure_launched():135] starting backend process...
2023-06-14 14:48:13,696 INFO    MainThread:10134 [backend.py:ensure_launched():139] started backend process with pid: 10189
2023-06-14 14:48:13,699 INFO    MainThread:10134 [wandb_init.py:init():429] backend started and connected
2023-06-14 14:48:13,701 INFO    MainThread:10134 [wandb_init.py:init():477] updated telemetry
2023-06-14 14:48:13,701 INFO    MainThread:10134 [wandb_init.py:init():500] communicating current version
2023-06-14 14:48:14,798 INFO    MainThread:10134 [wandb_init.py:init():505] got version response 
2023-06-14 14:48:14,799 INFO    MainThread:10134 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2023-06-14 14:48:44,799 INFO    MainThread:10134 [interface.py:_communicate_run():651] couldn't get run from backend
2023-06-14 14:48:44,800 ERROR   MainThread:10134 [wandb_init.py:init():518] backend process timed out
2023-06-14 14:48:44,800 ERROR   MainThread:10134 [wandb_init.py:init():527] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
