Done.
Setting up the random seed for reproducibility...
Done.
dynamic_import - class_name:  OracleTrainer
Initializing model...
Done.
Initializing datasets...
Done.
Initializing clients...
dynamic_import - class_name:  OracleClient
Done.
Initializing server...
dynamic_import - class_name:  OracleServer
Running without server optimizer
Done.
Initialize return score, metrics, ckpt, ckpt step...
Setting up metrics...
Done.
Done.
Initializing optimizer and scheduler...
Done.
dynamic_import - class_name:  OracleClient
The experiment begins...
ROUND 1/15: Training 2 Clients...
CLIENT 1/2: erfurt5 RGB
EPOCH 1: ended.
end
CLIENT 2/2: weimar3 HHA
EPOCH 1: ended.
end
{'Total samples': array(56), 'Overall Acc': 0.30563096334313894, 'Mean Acc': 0.08740423779806358, 'Mean Precision': 0.09249246524419197, 'FreqW Acc': 0.19089791957342916, 'Mean IoU': 0.045879892173141965, 'Class IoU': {0: 0.273096141464953, 1: 0.1349173679864517, 2: 0.2575689715445217, 3: 0.0, 4: 0.0, 5: 0.012112108912718925, 6: 0.0, 7: 0.0, 8: 0.02958950572357059, 9: 0.0, 10: 0.013390704471487682, 11: 0.00995278638776662, 12: 0.0, 13: 0.0034506882788012468, 14: 'X', 15: 'X', 16: 'X', 17: 0.0, 18: 0.0}, 'Class Acc': {0: 0.46657313820804863, 1: 0.1440215963010783, 2: 0.4108190728643048, 3: 0.0, 4: 0.0, 5: 0.013813463570586673, 6: 0.0, 7: 0.0, 8: 0.036844911499098194, 9: 0.0, 10: 0.25197288370408577, 11: 0.07044339534988228, 12: 0.0, 13: 0.003979343271932264, 14: 'X', 15: 'X', 16: 'X', 17: 0.0, 18: 0.0}, 'Class Prec': {0: 0.3970731841287931, 1: 0.6809479313636361, 2: 0.4084477356572089, 3: 0.0, 4: 0.0, 5: 0.08953460900318104, 6: 0.0, 7: 0.0, 8: 0.13063398643996654, 9: 0.0, 10: 0.013945058623860624, 11: 0.01145756485334424, 12: 0.0, 13: 0.025316769569656655, 14: 'X', 15: 'X', 16: 'X', 17: 0.0, 18: 0.0}}
QUI ARRIVA ALL'UPDATE
AGGREGATION: END OF THE ROUND
Traceback (most recent call last):
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 53, in <module>
    run_experiment()
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 21, in run_experiment
    max_score = trainer.train(*trainer.train_args, **trainer.train_kwargs)
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 136, in train
    return self.perform_fed_oracle_training(
Traceback (most recent call last):
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 53, in <module>
    run_experiment()
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 21, in run_experiment
    max_score = trainer.train(*trainer.train_args, **trainer.train_kwargs)
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 136, in train
    return self.perform_fed_oracle_training(
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 81, in perform_fed_oracle_training
    self.server.update_model()
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/servers/oracle_server.py", line 266, in update_model
    self.model.module.hha_backbone.load_state_dict(averaged_sol_n_hha)
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/servers/oracle_server.py", line 266, in update_model
    self.model.module.hha_backbone.load_state_dict(averaged_sol_n_hha)
  File "_pydevd_bundle/pydevd_cython.pyx", line 1589, in _pydevd_bundle.pydevd_cython.ThreadTracer.__call__
  File "_pydevd_bundle/pydevd_cython.pyx", line 929, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch
  File "_pydevd_bundle/pydevd_cython.pyx", line 920, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch
  File "_pydevd_bundle/pydevd_cython.pyx", line 317, in _pydevd_bundle.pydevd_cython.PyDBFrame.do_wait_suspend
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1160, in do_wait_suspend
    self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread)
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1175, in _do_wait_suspend
    time.sleep(0.01)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 2195, in <module>
    main()
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 2179, in main
    handle_keyboard_interrupt()
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1997, in handle_keyboard_interrupt
    traceback.print_exception(type(value), value, tb, limit=limit)
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/traceback.py", line 105, in print_exception
    print(line, file=file, end="")
KeyboardInterrupt