Done.
Setting up the random seed for reproducibility...
Done.
dynamic_import - class_name:  OracleTrainer
Initializing model...
Done.
Initializing datasets...
Done.
Initializing clients...
dynamic_import - class_name:  OracleClient
Done.
Initializing server...
dynamic_import - class_name:  OracleServer
Running without server optimizer
Done.
Initialize return score, metrics, ckpt, ckpt step...
Setting up metrics...
Done.
Done.
Initializing optimizer and scheduler...
Done.
dynamic_import - class_name:  OracleClient
The experiment begins...
ROUND 1/1: Training 3 Clients...
CLIENT 1/3: erfurt5 RGB
fine
fine
fine
EPOCH 1: ended.
end
CLIENT 2/3: weimar3 HHA
fine
fine
fine
fine
EPOCH 1: ended.
end
CLIENT 3/3: strasbourg3 HHA
fine
fine
fine
fine
fine
fine
fine
fine
fine
fine
fine
EPOCH 1: ended.
end
{'Total samples': array(144), 'Overall Acc': 0.3454455845482759, 'Mean Acc': 0.09863415243008891, 'Mean Precision': 0.0773112110398943, 'FreqW Acc': 0.21807294417467996, 'Mean IoU': 0.05837988563615438, 'Class IoU': {0: 0.38434900695926727, 1: 0.05798411745219391, 2: 0.23822033980962395, 3: 0.0, 4: 0.0, 5: 0.0, 6: 0.0, 7: 0.0, 8: 0.05125474272747617, 9: 0.0, 10: 0.0328532380149229, 11: 0.0, 12: 'X', 13: 0.052656953942677144, 14: 'X', 15: 'X', 16: 'X', 17: 'X', 18: 0.0}, 'Class Acc': {0: 0.627049896252291, 1: 0.07499585489449621, 2: 0.351822225295964, 3: 0.0, 4: 0.0, 5: 0.0, 6: 0.0, 7: 0.0, 8: 0.06616711923773617, 9: 0.0, 10: 0.17419175027263825, 11: 0.0, 12: 'X', 13: 0.08665128806811928, 14: 'X', 15: 'X', 16: 'X', 17: 'X', 18: 0.0}, 'Class Prec': {0: 0.4982480254307179, 1: 0.20358175012546592, 2: 0.4245473676872722, 3: 0.0, 4: 0.0, 5: 0.0, 6: 0.0, 7: 0.0, 8: 0.18528321862973957, 9: 0.0, 10: 0.03891413984155007, 11: 0.0, 12: 'X', 13: 0.11833850804324597, 14: 'X', 15: 'X', 16: 'X', 17: 'X', 18: 0.0}}
QUI ARRIVA ALL'UPDATE
AGGREGATION: END OF THE ROUND
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 53, in <module>
    run_experiment()
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 21, in run_experiment
    max_score = trainer.train(*trainer.train_args, **trainer.train_kwargs)
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 136, in train
    return self.perform_fed_oracle_training(
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 81, in perform_fed_oracle_training
    self.server.update_model()
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/servers/oracle_server.py", line 298, in update_model
    self.updates_rgb = []
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/servers/oracle_server.py", line 298, in update_model
    self.updates_rgb = []
  File "_pydevd_bundle/pydevd_cython.pyx", line 1179, in _pydevd_bundle.pydevd_cython.SafeCallWrapper.__call__
  File "_pydevd_bundle/pydevd_cython.pyx", line 620, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch
  File "_pydevd_bundle/pydevd_cython.pyx", line 929, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch
  File "_pydevd_bundle/pydevd_cython.pyx", line 920, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch
  File "_pydevd_bundle/pydevd_cython.pyx", line 317, in _pydevd_bundle.pydevd_cython.PyDBFrame.do_wait_suspend
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1160, in do_wait_suspend
    self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread)
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1175, in _do_wait_suspend
    time.sleep(0.01)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 2195, in <module>
    main()
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 2179, in main
    handle_keyboard_interrupt()
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1997, in handle_keyboard_interrupt
    traceback.print_exception(type(value), value, tb, limit=limit)
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/traceback.py", line 105, in print_exception
    print(line, file=file, end="")
KeyboardInterrupt