Done.
Setting up the random seed for reproducibility...
Done.
class_name:  OracleTrainer
Initializing model...
Done.
Initializing datasets...
Done.
Initializing clients...
class_name:  OracleClient
Done.
Initializing server...
class_name:  OracleServer
Running without server optimizer
Done.
Initialize return score, metrics, ckpt, ckpt step...
Setting up metrics...
Done.
Done.
Initializing optimizer and scheduler...
Done.
Generating sample ids for plots...
Done.
class_name:  OracleClient
The experiment begins...
ROUND 1/2: Training 2 Clients...
CLIENT 1/2: erfurt5 RGB
EPOCH 1: ended.
CLIENT 2/2: weimar3 RGB
EPOCH 1: ended.
ROUND 2/2: Training 2 Clients...
CLIENT 1/2: dusseldorf4 RGB
EPOCH 1: ended.
CLIENT 2/2: dusseldorf1 HHA
EPOCH 1: ended.
Testing...
Client 1/1 - test_user HHA
test_user HHA: 20/500, 4.0%
test_user HHA: 40/500, 8.0%
test_user HHA: 60/500, 12.0%
test_user HHA: 80/500, 16.0%
test_user HHA: 100/500, 20.0%
test_user HHA: 120/500, 24.0%
test_user HHA: 140/500, 28.0%
test_user HHA: 160/500, 32.0%
test_user HHA: 180/500, 36.0%
test_user HHA: 200/500, 40.0%
test_user HHA: 220/500, 44.0%
test_user HHA: 240/500, 48.0%
test_user HHA: 260/500, 52.0%
test_user HHA: 280/500, 56.0%
test_user HHA: 300/500, 60.0%
test_user HHA: 320/500, 64.0%
test_user HHA: 340/500, 68.0%
test_user HHA: 360/500, 72.0%
test_user HHA: 380/500, 76.0%
test_user HHA: 400/500, 80.0%
test_user HHA: 420/500, 84.0%
test_user HHA: 440/500, 88.0%
test_user HHA: 460/500, 92.0%
test_user HHA: 480/500, 96.0%
test_user HHA: 500/500, 100.0%
Done.
New best result found at round 2
Test mean iou at round 2: 2.028%
Training completed.
Final mIoU: 2.028%
Traceback (most recent call last):
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 49, in <module>
    run_experiment()
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 30, in run_experiment
    dist_utils.cleanup()
KeyboardInterrupt
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_constants.py", line 58, in dummy_excepthook
    def dummy_excepthook(exctype, value, traceback):
KeyboardInterrupt
Original exception was:
Traceback (most recent call last):
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 2195, in <module>
    main()
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 2177, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1489, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 49, in <module>
    run_experiment()
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 30, in run_experiment
    dist_utils.cleanup()
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 30, in run_experiment
    dist_utils.cleanup()
  File "_pydevd_bundle/pydevd_cython.pyx", line 1589, in _pydevd_bundle.pydevd_cython.ThreadTracer.__call__
  File "_pydevd_bundle/pydevd_cython.pyx", line 929, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch
  File "_pydevd_bundle/pydevd_cython.pyx", line 920, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch
  File "_pydevd_bundle/pydevd_cython.pyx", line 317, in _pydevd_bundle.pydevd_cython.PyDBFrame.do_wait_suspend
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1160, in do_wait_suspend
    self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread)
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1175, in _do_wait_suspend
    time.sleep(0.01)
KeyboardInterrupt